### ISSUE TITLE
Installation fails with Python 3.7

### ISSUE THREAD

**Issue by adamjstewart** [mrzechonek/tut-framework#18]
Installation with Python 3.7 results in the following error:
```console
Traceback (most recent call last):
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-nxope4ko/spack-src/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Scripting.py", line 114, in waf_entry_point
    run_commands()
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-nxope4ko/spack-src/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Scripting.py", line 171, in run_commands
    parse_options()
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-nxope4ko/spack-src/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Scripting.py", line 144, in parse_options
    Context.create_context('options').execute()
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-nxope4ko/spack-src/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Options.py", line 146, in execute
    super(OptionsContext,self).execute()
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-nxope4ko/spack-src/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-nxope4ko/spack-src/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-nxope4ko/spack-src/wscript", line 11, in options
    opt.load('compiler_cxx')
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-nxope4ko/spack-src/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Context.py", line 90, in load
    fun(self)
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-nxope4ko/spack-src/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Tools/compiler_cxx.py", line 36, in options
    opt.load_special_tools('cxx_*.py')
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-nxope4ko/spack-src/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Context.py", line 321, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-nxope4ko/spack-src/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Node.py", line 361, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-nxope4ko/spack-src/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Node.py", line 361, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
```
This is due to a bug in `waf` that was fixed about [a year ago](https://gitlab.com/ita1024/waf/commit/facdc0b173d933073832c768ec1917c553cb369c).

Can you update to the latest version of `waf` so `tut` can be built with the latest version of `python`?

**Comment by mrzechonek** [comment]
Sure, I'll try - hopefully waf didn't change the API again ;)

**Comment by adamjstewart** [comment]
@mrzechonek any updates on this? Python 3.8 is now out as well.

**Comment by adamjstewart** [comment]
@mrzechonek any updates? Python 3.9 is now out, and 3.10 is around the corner...

**Comment by mrzechonek** [comment]
My 2nd kid is also out (-;

**Comment by adamjstewart** [comment]
3.10 is now out...

**Comment by mrzechonek** [comment]
Well, at this point all I can say is that I'm happy to accept a PR. Sorry, life happens.
