### ISSUE TITLE
port wscript to newer waf

### ISSUE THREAD

**Issue by rathann** [mrzechonek/tut-framework#6]
The bundled waf is very old (1.5.12) while the current version is 1.8.8. The included wscript doesn't work with waf version 1.8.8:
$ waf --help
Waf: The wscript in '/builddir/build/BUILD/tut-framework-2013-12-18' is unreadable
Traceback (most recent call last):
  File "/usr/share/waf/waflib/Scripting.py", line 92, in waf_entry_point
    set_main_module(os.path.join(Context.run_dir,Context.WSCRIPT_FILE))
  File "/usr/share/waf/waflib/Scripting.py", line 117, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/usr/share/waf/waflib/Context.py", line 328, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/builddir/build/BUILD/tut-framework-2013-12-18/wscript", line 6, in <module>
    import Options
ImportError: No module named Options

**Comment by mrzechonek** [comment]
Thanks for the report and sorry it took so long.
